feat(.github): git action fixed

diff --git a/.github/workflows/git_action.yaml b/.github/workflows/git_action.yaml
--- a/.github/workflows/git_action.yaml
+++ b/.github/workflows/git_action.yaml
@@ -1,5 +1,5 @@
 name: GitHub Action MyRPG
-run-name: ${{ github.actor }} is ${{ github.event_name }}ing on the ${{ github.ref_name }} branch ✘
+run-name: ${{ github.actor }} is ${{ github.event_name }}ing on ${{ github.ref_name }} branch ✘
 
 on:
   workflow_dispatch:
@@ -24,118 +24,123 @@ env:
   FOURTH_AT: '441612891548942337'
   FIFTH_NAME: NULL
   FIFTH_AT: NULL
-  CUSTOM_IMAGE: https://cdn.discordapp.com/attachments/1173625780186652702/1230601113816797216/robot-removebg-preview.png?ex=6633e998&is=66217498&hm=2cbe28799df3572c954c540d326d1d30f018bb5db833e643adea75786beeef9a&
+  CUSTOM_IMAGE: https://cdn.discordapp.com/attachments/1229787418031427647/1237526646429585450/robot-removebg-preview.png?ex=663bf800&is=663aa680&hm=63f12e3de6594db4e54f4481a35ce455bf73d45b82e558ccce6ced5475528b9d&
 # ssh key to set as scret: GIT_SSH_PRIVATE_KEY
 # webhhok link to set as scret: DISCORD_WEBHOOK
 jobs:
   check_commit:
-    runs-on: ubuntu-latest
     if: ${{ github.repository_owner != 'EpitechPromo2028' }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - run: echo -ne "**Commit** standart not respected ! " > failed_task.txt
-      - uses: actions/upload-artifact@v2
+      - uses: webiny/action-conventional-commits@v1.3.0
+      - if: ${{ failure() }}
+        run: echo -ne "**Commit** standart not respected ! " > error.txt
+      - name: Upload error
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4
         with:
-          name: failed_task
-          path: failed_task.txt
-      - uses: webiny/action-conventional-commits@v1.2.0
-      - run: echo -ne "" > failed_task.txt
-      - uses: actions/upload-artifact@v2
-        with:
-          name: failed_task
-          path: failed_task.txt
+          name: task_commit
+          path: error.txt
+      - if: ${{ failure() }}
+        run: exit 1
 
   check_repository_size:
-    needs: check_commit
+    if: ${{ github.repository_owner != 'EpitechPromo2028' }}
     runs-on: ubuntu-latest
-    container: epitechcontent/epitest-docker
     env:
       EXIT: false
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v2
-        with:
-          name: failed_task
+      - name: Set env variable
+        run: echo "SIZE=$(du -s --exclude=.git | awk '{print $1}')" >> $GITHUB_ENV
       - name: Check size
         run: |
-          SIZE=$(du -s --exclude=.git | awk '{print $1}')
           if [ $SIZE -gt $MAX_SIZE ]; then
-            echo "::error title=Repo size over $MAX_SIZE"B" !::🚫 Actual: $SIZE"B""
-            echo -ne "Repository **size** excess ! " >> failed_task.txt
             echo "EXIT=true" >> $GITHUB_ENV
           fi
-      - uses: actions/upload-artifact@v2
+      - if: ${{ env.EXIT == 'true' }}
+        run: |
+          echo "::error title=Repo size over $MAX_SIZE"B" !::🚫 Actual: $SIZE"B""
+          echo -ne "Repository **size** excess ! " > error.txt
+      - name: Upload errors
+        if: ${{ env.EXIT == 'true' }}
+        uses: actions/upload-artifact@v4
         with:
-          name: failed_task
-          path: failed_task.txt
-      - run: if [ $EXIT == true ]; then exit 1; fi
+          name: task_repo_size
+          path: error.txt
+      - if: ${{ env.EXIT == 'true' }}
+        run: exit 1
 
   check_coding_style:
-    needs: check_commit
+    if: ${{ github.repository_owner != 'EpitechPromo2028' }}
     runs-on: ubuntu-latest
     container: ghcr.io/epitech/coding-style-checker:latest
     env:
       EXIT: false
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v2
-        with:
-          name: failed_task
       - name: Coding style
         run: check.sh $(pwd) $(pwd)
+      - name: Set env variable
+        run: echo "NB_ERRORS=$(cat coding-style-reports.log | wc -l)" >> $GITHUB_ENV
       - name: Display coding style errors
         run: |
-          NB_ERRORS=$(cat coding-style-reports.log | wc -l)
           if [ $NB_ERRORS -ge 1 ]; then
             while IFS= read -r line
-              do
-                FILE=$(echo $line | cut -d ':' -f 1)
-                LINE=$(echo $line | cut -d ':' -f 2)
-                TYPE=$(echo $line | cut -d ':' -f 3)
-                ERROR=$(echo $line | cut -d ':' -f 4)
+            do
+              FILE=$(echo $line | cut -d ':' -f 1)
+              LINE=$(echo $line | cut -d ':' -f 2)
+              TYPE=$(echo $line | cut -d ':' -f 3)
+              ERROR=$(echo $line | cut -d ':' -f 4)
               echo "::error file=$FILE,line=$LINE,title=$ERROR coding style error::❌ $TYPE"
             done < coding-style-reports.log
-              echo "::error title=Coding style errors !::🚫 $NB_ERRORS errors"
-              echo -ne "Coding **style** errors ! " >> failed_task.txt
-              echo "EXIT=true" >> $GITHUB_ENV
+            echo "EXIT=true" >> $GITHUB_ENV
           fi
-      - uses: actions/upload-artifact@v2
+      - if: ${{ env.EXIT == 'true' }}
+        run: |
+          echo "::error title=Coding style errors !::🚫 $NB_ERRORS errors"
+          echo -ne "Coding **style** errors ! " > error.txt
+      - name: Upload errors
+        if: ${{ env.EXIT == 'true' }}
+        uses: actions/upload-artifact@v4
         with:
-          name: failed_task
-          path: failed_task.txt
-      - run: if [ $EXIT == true ]; then exit 1; fi
+          name: task_coding_style
+          path: error.txt
+      - if: ${{ env.EXIT == 'true' }}
+        run: exit 1
 
   check_compilation:
-    needs: check_commit
+    if: ${{ github.repository_owner != 'EpitechPromo2028' }}
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
     env:
       EXIT: false
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v2
-        with:
-          name: failed_task
       - name: Compilation
         timeout-minutes: 2
-        run: make
-      - name: Clear .o
-        run: make clean
+        run: make && make clean
       - name: Check executables
         run: |
           if [ ! -x $EXECUTABLE ]; then
-            echo "::error title=Compilation error !::🚫 $EXECUTABLE not executable"
-            echo -ne "Program not **compiling** ! " >> failed_task.txt
             echo "EXIT=true" >> $GITHUB_ENV
           fi
-      - uses: actions/upload-artifact@v2
+      - if: ${{ failure() || env.EXIT == 'true' }}
+        run: |
+          echo "::error title=Compilation error !::🚫 $EXECUTABLE not executable"
+          echo -ne "Program not **compiling** ! " > error.txt
+      - name: Upload error
+        if: ${{ failure() || env.EXIT == 'true' }}
+        uses: actions/upload-artifact@v4
         with:
-          name: failed_task
-          path: failed_task.txt
-      - run: if [ $EXIT == true ]; then exit 1; fi
+          name: task_compilation
+          path: error.txt
+      - if: ${{ failure() || env.EXIT == 'true' }}
+        run: exit 1
 
   push_to_mirror:
-    needs: [ check_repository_size, check_coding_style, check_compilation ]
+    needs: [ check_commit, check_repository_size, check_coding_style, check_compilation ]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -148,43 +153,11 @@ jobs:
           ssh_private_key:
             ${{ secrets.GIT_SSH_PRIVATE_KEY }}
 
-  webhook_request_done:
-    runs-on: ubuntu-latest
-    needs: push_to_mirror
-    if: ${{ success() }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Send a request to webhook
-        run: |
-          HASH=$(git rev-parse --short "$GITHUB_SHA")
-          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
-            "username": "${{ github.event.head_commit.message }}",
-            "content": "",
-            "embeds": [{
-                "type": "rich",
-                "description": "${{ github.event_name }}ed on **${{ github.ref_name }}**",
-                "color": 65280,
-                "author": {
-                  "name": "${{ github.actor }}",
-                  "url": "https://github.com/${{ github.actor }}",
-                  "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
-                },
-                "footer": {
-                  "text": "commit hash: '$HASH'"
-                }
-            }]
-            }' ${{ secrets.DISCORD_WEBHOOK }})
-            echo "Webhook server response: $RESPONSE"
-
-  webhook_request_failed:
-    runs-on: ubuntu-latest
-    needs: push_to_mirror
+  setup_fail_webhook:
+    needs: [ check_commit, check_repository_size, check_coding_style, check_compilation ]
     if: ${{ failure() }}
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v2
-        with:
-          name: failed_task
       - name: Choose mention
         run: |
           if [ ${{ github.actor }} == $FIRST_NAME ]; then
@@ -198,29 +171,53 @@ jobs:
           elif [ ${{ github.actor }} == $FIFTH_NAME ]; then
             MENTION="<@$FIFTH_AT>"
           else
-            MENTION=@everyone
+            MENTION="@everyone"
           fi
-          echo "MENTION=$MENTION" >> $GITHUB_ENV
+          echo -ne "$MENTION" > mention.txt
+      - name: Upload settings
+        uses: actions/upload-artifact@v4
+        with:
+          name: settings
+          path: mention.txt
+
+  webhook_request:
+    needs: setup_fail_webhook
+    if: ${{ always() && github.repository_owner != 'EpitechPromo2028' }}
+    runs-on: ubuntu-latest
+    env:
+      COLOR: 65280
+      TEXT: "${{ github.event_name }}ed on **${{ github.ref_name }}**"
+    steps:
+      - uses: actions/checkout@v4
+      - name: Download
+        uses: actions/download-artifact@v4
+      - name: Get settings
+        run: |
+          if [ -d settings ]; then
+            echo "MENTION=$(cat settings/mention.txt)" >> $GITHUB_ENV
+            echo "ERROR=$(cat task_*/error.txt)" >> $GITHUB_ENV
+            echo "COLOR=$(echo -ne "16711680")" >> $GITHUB_ENV
+            echo "TEXT=$(echo -ne "failed to ${{ github.event_name }} on **${{ github.ref_name }}**")" >> $GITHUB_ENV
+            echo "IMAGE=$CUSTOM_IMAGE" >> $GITHUB_ENV
+          fi;
       - name: Send a request to webhook
         run: |
-          echo -ne "\n" >> failed_task.txt
-          FAILED_TASK=$(cat failed_task.txt)
           HASH=$(git rev-parse --short "$GITHUB_SHA")
           RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
             "username": "${{ github.event.head_commit.message }}",
-            "content": "'$MENTION'",
+            "content": "'"$MENTION"'",
             "embeds":
             [
               {
                 "type": "rich",
-                "title": "'"$FAILED_TASK"'",
-                "description": "failed to ${{ github.event_name }} on **${{ github.ref_name }}**",
-                "color": 16711680,
+                "title": "'"$ERROR"'",
+                "description": "'"$TEXT"'",
+                "color": '"$COLOR"',
                 "thumbnail": {
-                  "url": "'$CUSTOM_IMAGE'"
+                  "url": "'"$IMAGE"'"
                 },
                 "footer": {
-                  "text": "commit hash: '$HASH'"
+                  "text": "commit hash: '"$HASH"'"
                 },
                 "author": {
                   "name": "${{ github.actor }}",
